version: "3"

services:

  app:
    build:
      context: .
    container_name: bookanna.api
    env_file: app/app.env
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: >
      sh -c  "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file: local_db.env

