# Generated by Django 3.1 on 2020-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
